# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Onedrive/OneDrive - UNSW/My Onedrive/PhD/Src/New-Delay-Sensor/1LUT-Kria260/project_v0/project_v0.srcs/sources_1/bd/design_1/ip/design_1_top_0_1/design_1_top_0_1.xci
# IP: The module: 'design_1_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Onedrive/OneDrive - UNSW/My Onedrive/PhD/Src/New-Delay-Sensor/1LUT-Kria260/project_v0/project_v0.gen/sources_1/bd/design_1/ip/design_1_top_0_1/src/const3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Onedrive/OneDrive - UNSW/My Onedrive/PhD/Src/New-Delay-Sensor/1LUT-Kria260/project_v0/project_v0.srcs/sources_1/bd/design_1/ip/design_1_top_0_1/design_1_top_0_1.xci
# IP: The module: 'design_1_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Onedrive/OneDrive - UNSW/My Onedrive/PhD/Src/New-Delay-Sensor/1LUT-Kria260/project_v0/project_v0.gen/sources_1/bd/design_1/ip/design_1_top_0_1/src/const3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
